name: Build Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: >-
          docker build
          --build-arg ADMIN_PASSWORD=password
          --build-arg GITHUB_TOKEN=${{ secrets.PRO_GITHUB_TOKEN }}
          -f pro.Dockerfile
          -t opentrader/opentrader:latest .

      - name: Push Docker Image
        run: docker push opentrader/opentrader:latest
